# Generated by Django 2.1 on 2020-02-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Govtjob_detail_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('post_name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('total_post', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('last_date', models.CharField(max_length=100)),
            ],
        ),
    ]
